mysite/gomoto/urls.py
from django.urls import path
from . import views
app_name = 'gomoto'
urlpatterns = [
    path('', views.index, name='index'),
    path('get_bikes', views.get_bikes, name='get_bikes'),
]

mysite/lobosevents/urls.py
from django.urls import path, include

from . import views

app_name = 'lobosevents'

urlpatterns = [

    path('profile/', views.profile, name='profile'),
    path('register/', views.register, name='register'),
    path('login_register/', views.login_register, name='login_register'),
    path('login/', views.mylogin, name='login'),
    path('logout/', views.mylogout, name='logout'),
    path('register/', views.register, name='register'),
    path('event_registration/', views.event_registration, name='event_registration'),
    path('heroes/', views.heroes, name='heroes_changelist'),
    path('cancelorder/', views.cancelorder, name='cancelorder'),
    path('eventconfir/', views.event_reg_confirmation, name='event_reg_confirmation'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gomoto.urls')),
    path('', include('lobosevents.urls')),

]
admin.site.site_header = "Lobos Events Database"
admin.site.site_title = "Lobos MC"
admin.site.index_title = "Lobos Events Database"

mysite/lobosevents/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver



# Create your models here.

#   V--->--hooks extends-->---V
# User (not seen) 1----1-> Profile -1----M-> UserEvent -1----M-> Event -1----M-> SpecialTests -M----1-> UserSpecialTests -M----1->|
#  ^----------------<-----------------------<------------------------<---------------------------<----------------------------------<-V


# https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html#proxy

class Profile(models.Model):
    FEMALE = 'Female'
    MALE = 'Male'

    GENDER = (
        (FEMALE, 'Female'),
        (MALE, 'Male'),
    )

    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    gender = forms.ChoiceField(choices=GENDER, widget=forms.RadioSelect())
    birth_date = models.DateField(null=True, blank=True)

    # twilio 'Lookup' API
    phone_number = models.CharField(max_length=300, null=True, blank=True)
    country = models.CharField(max_length=300, null=True, blank=True)
    address = models.CharField(max_length=300, null=True, blank=True)
    address_line_two = models.CharField(max_length=300, null=True, blank=True)
    city = models.CharField(max_length=300, null=True, blank=True)
    state = models.CharField(max_length=300, null=True, blank=True)
    zip_code = models.CharField(max_length=300, null=True, blank=True)

    # todo every event or keep on the user profile?
    # e_c = emergemcy contact
    emergency_contact_name = models.CharField(max_length=300, null=True, blank=True)

    # twilio 'Lookup' API
    emergency_contact_contact = models.CharField(max_length=300, null=True, blank=True)

    # https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html#proxy

    # @receiver(post_save, sender=User)
    # def create_user_profile(sender, instance, created, **kwargs):
    #     if created:
    #         Profile.objects.create(user=instance)
    #
    # @receiver(post_save, sender=User)
    # def save_user_profile(sender, instance, **kwargs):
    #     instance.profile.save()

    def __str__(self):
        return str(self.user) + ' Contact Info'


class Event(models.Model):
    event_name = models.CharField(max_length=300, null=True, blank=True)
    event_date = models.DateField(max_length=300, null=True, blank=True)
    # could be added
    pro_time_est = models.TimeField(max_length=300, null=True, blank=True)
    am_time_est = models.TimeField(max_length=300, null=True, blank=True)

    def __str__(self):

        return str(self.event_name) + ' ' + str(self.event_date)[0:4]


class SpecialTest(models.Model):
    event = models.ForeignKey(Event, null=True, blank=True, on_delete=models.CASCADE)
    special_test_num = models.IntegerField(max_length=30, null=True, blank=True)

    def __str__(self):
        return str(self.event)+ ' - ' + ' Special Test ' + str(self.special_test_num)


class UserEvent(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    bike_year = models.IntegerField(null=True, blank=True)
    bike_make = models.CharField(max_length=300, null=True, blank=True)
    bike_model = models.CharField(max_length=300, null=True, blank=True)
    bike_displacement = models.IntegerField(null=True, blank=True)
    placard = models.IntegerField(null=True, blank=True)
    confirmation = models.CharField(max_length=300, null=True, blank=True)

    # todo every event or put on the user profile?
    omra_number = models.IntegerField()
    ama_number = models.IntegerField()

    def __str__(self):
        return str(self.user) + ' - ' + str(self.event)+ ' - ' + str(self.placard)


class UserSpecialTest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    specialtest = models.ForeignKey(SpecialTest, on_delete=models.CASCADE)
    start_time = models.TimeField(max_length=300, null=True, blank=True)
    stop_time = models.TimeField(max_length=300, null=True, blank=True)

    def __str__(self):
        return str(self.user) + ' ' + str(self.specialtest)



class Person(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField(blank=True)
    birth_date = models.DateField()
    location = models.CharField(max_length=100, blank=True)

mysite/lobosevents/views.py
from django.contrib.auth.models import User
from django.contrib.auth import logout, authenticate, login
from .decorators import check_recaptcha
from django.shortcuts import render, reverse
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.contrib.auth import authenticate
from tablib import Dataset
from .resources import PersonResource
from django.core.mail import send_mail


def index(request):
    return render(request, 'lobosevents/event_registration.html')


def heroes(request):
    return render(request, 'lobosevents/heroes_changelist.html')


def cancelorder(request):
    return render(request, 'lobosevents/cancelorder.html')


def event_reg_confirmation(request):
    return render(request, 'lobosevents/event_reg_confirmation.html')


def profile(request):
    return render(request, 'lobosevents/profile.html')




# @login_required
def event_registration(request):
    return render(request, 'lobosevents/event_registration.html')

    # todo_text = request.POST['todo_item_id_key_in_template']
    # todo_item = TodoItem.objects.get(pk=todo_text)
    # todo_item.delete()
    # # item_on_list = question.choice_set.get(pk=request.POST['choice'])
    # # save data from request.POST in database
    # # redirect back to the index page (HttpResponseRedirect)
    #
    # return HttpResponseRedirect(reverse('lobosevents:event_registration'))


@check_recaptcha
def register(request):
    if not request.recaptcha_is_valid:
        return HttpResponseRedirect(reverse('lobosevents:login_register')+'?message=bad_recaptcha')
    username = request.POST['username']
    email = request.POST['email']
    password = request.POST['password']
    user = User.objects.create_user(username, email, password)
    login(request, user)
    send_mail(
        'Subject here',
        'Here is the message.',
        'from@example.com',
        ['to@example.com'],
        fail_silently=False,
    )

    return HttpResponseRedirect(reverse('lobosevents:index'))


@check_recaptcha
def mylogin(request):
    if not request.recaptcha_is_valid:
        return HttpResponseRedirect(reverse('lobosevents:login_register')+'?message=bad_recaptcha')
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)


    if user is not None:
        login(request, user)
        if 'next' in request.POST and request.POST['next'] != '':
            return HttpResponseRedirect(request.POST['next'])
        return HttpResponseRedirect(reverse('lobosevents:index'))
    return HttpResponseRedirect(reverse('lobosevents:login_register'))


def mylogout(request):
    logout(request)
    return HttpResponseRedirect(reverse('lobosevents:login_register'))



def login_register(request):
    message = request.GET.get('message', '')
    next = request.GET.get('next', '')
    return render(request, 'lobosevents/login_register.html', {'next': next, 'message': message})


def simple_upload(request):
    if request.method == 'POST':
        person_resource = PersonResource()
        dataset = Dataset()
        new_persons = request.FILES['myfile']

        imported_data = dataset.load(new_persons.read())
        result = person_resource.import_data(dataset, dry_run=True)  # Test the data import

        if not result.has_errors():
            person_resource.import_data(dataset, dry_run=False)  # Actually import now

    return render(request, 'core/simple_upload.html')




# send_mail(
#     'Subject here',
#     'Here is the message.',
#     'from@example.com',
#     ['to@example.com'],
#     fail_silently=False,
# )

mysite/lobosevents/templates/lobosevents/cancelorder.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Canceled Order</title>
</head>
<body>
Canceled. You did not complete the registration process
If you would like to register please go to <a href="{% url 'lobosevents:event_registration' %}"> register </a>
</body>
</html>

mysite/lobosevents/templates/lobosevents/csv_form.html
{% extends 'admin/base.html' %}

{% block content %}
    <div>
        <form action="." method="POST" enctype="multipart/form-data">
            {{ form.as_p }}
            {% csrf_token %}

                <button type="submit">Upload CSV</button>
        </form>
    </div>
    <br />

{% endblock %}

mysite/lobosevents/templates/lobosevents/event_reg_confirmation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Event Registration Confirmation</title>
</head>
<body>
Congratulations! You have registered for the event. Your confirmation number if event. <a href="{% url 'lobosevents/profile.html' %}">Profile</a>
</body>
</html>

mysite/lobosevents/templates/lobosevents/heroes_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools %}
    <a href="import-csv/">Import CSV</a>
    <br />
    {{ block.super }}
{% endblock %}

mysite/lobosevents/templates/lobosevents/import.html
{% extends 'base.html' %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>
{% endblock %}

mysite/lobosevents/templates/lobosevents/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>

    <script src='https://www.google.com/recaptcha/api.js'></script>

</head>
<body>

<section class="section">
    <div class="container">
        <h2>Register</h2>
        {% if message == 'bad_recaptcha' %}
        <h3 style="color:red">Please select the Recaptcha</h3>
        {% endif %}
        <form action="{% url 'lobosevents:register' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{next}}"/>
            <input type="text" name="username" placeholder="username" required/>
            <input type="text" name="email" placeholder="email" required/>
            <input type="password" name="password" placeholder="password" required/>
            <script src='https://www.google.com/recaptcha/api.js'></script>
            <div class="g-recaptcha" data-sitekey="6Lc8dWEUAAAAABjUdXmBSCkJ3lf4BNyXQQyC9MMq"></div>
            <input type="submit" value="register"/>
        </form>
    </div>
</section>

</body>
</html>

mysite/lobosevents/templates/lobosevents/login_register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login / Register</title>
    <style>
        body {
            margin-left: 30px;
        }
    </style>
    <script src='https://www.google.com/recaptcha/api.js'></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
</head>
<body>
<section class="section">
    <div class="container">


        <h2>Register</h2>
        {% if message == 'bad_recaptcha' %}
        <h3 style="color:red">Please select the Recaptcha</h3>
        {% endif %}
        <form action="{% url 'lobosevents:register' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{next}}"/>
            <input type="text" name="username" placeholder="username" required/>
            <input type="text" name="email" placeholder="email" required/>
            <input type="password" name="password" placeholder="password" required/>
            <script src='https://www.google.com/recaptcha/api.js'></script>
            <div class="g-recaptcha" data-sitekey="6LckA2UUAAAAAAqQPE4dgvsio1rqLHsDZkN28icC"></div>
            <input type="submit" value="register"/>
        </form>


        <h2>Login</h2>
        <form action="{% url 'lobosevents:login' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{next}}"/>
            <input type="text" name="username" placeholder="username" required/>
            <input type="password" name="password" placeholder="password" required/>
            <script src='https://www.google.com/recaptcha/api.js'></script>
            <div class="g-recaptcha" data-sitekey="6LckA2UUAAAAAAqQPE4dgvsio1rqLHsDZkN28icC"></div>
            <input type="submit" value="login"/>
        </form>

    </div>
</section>
</body>
</html>

mysite/lobosevents/templates/lobosevents/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<br>

Profile page of the user
<br>
<br>

... They will have to be registered and logged in to see their information
<br>
<br>

Will display the races they are registered for if they with confirmation number and the data they entered for the race


</body>
</html>

mysite/lobosevents/templates/lobosevents/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>

    <!--<script src='https://www.google.com/recaptcha/api.js'></script>-->

</head>
<body>

<section class="section">
    <div class="container">
        <h2>login</h2>
        <!--{% if message == 'bad_recaptcha' %}-->
        <h3 style="color:red">Please select the Recaptcha</h3>
        <!--{% endif %}-->
        <form method="post">
            <!--{% csrf_token %}-->
            <input type="hidden" name="next" value="{{next}}"/>
            <input type="text" name="username" placeholder="username" required/>
            <input type="text" name="email" placeholder="email" required/>
            <input type="password" name="password" placeholder="password" required/>
            <!--<script src='https://www.google.com/recaptcha/api.js'></script>-->
            <!--<div class="g-recaptcha" data-sitekey="6Lc8dWEUAAAAABjUdXmBSCkJ3lf4BNyXQQyC9MMq"></div>-->
            <input type="submit" value="register"/>
        </form>
    </div>
</section>

</body>
</html>

mysite/lobosevents/templates/lobosevents/soldout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Event Sold Out</title>
</head>
<body>

</body>
</html>

mysite/lobosevents/templates/lobosevents/user_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>

    <script src='https://www.google.com/recaptcha/api.js'></script>

</head>
<body>

<section class="section">
    <div class="container">
        <h2>Login</h2>
        <form action="{% url 'lobosevents:login' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{next}}"/>
            <input type="text" name="username" placeholder="username" required/>
            <input type="password" name="password" placeholder="password" required/>
            <script src='https://www.google.com/recaptcha/api.js'></script>
            <div class="g-recaptcha" data-sitekey="6Lc8dWEUAAAAABjUdXmBSCkJ3lf4BNyXQQyC9MMq"></div>
            <input type="submit" value="login"/>
        </form>
    </div>
</section>

</body>
</html>